from locators.main_locators import MainLocators
from locators.shopping_cart_link_locators import ShoppingCartLinkLocators
from locators.header_links_locators import HeaderLinksLocators
from locators.register_link_locators import RegisterLinkLocators
from locators.login_link_locators import LoginLinkLocators
from locators.wishlist_link_locators import WishlistLinkLocators