from pages.base_page import BasePage
from pages.main_page import MainPage
from pages.shopping_cart_link_page import ShoppingCartLinkPage
from pages.register_link_page import RegisterLinkPage
from pages.login_link_page import LoginLinkPage
from pages.wishlist_link_page import WishlistLinkPage